# Generated by Django 4.1.3 on 2022-12-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_class_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('ClassName', 'school')},
        ),
    ]
