# Generated by Django 4.1.3 on 2022-12-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_student_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='school',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Productincart',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
