# Generated by Django 4.1.3 on 2022-12-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_student_studetclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Male',
            field=models.BooleanField(default=False),
        ),
    ]
