# Generated by Django 4.1.3 on 2022-12-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_student_dob_user_female_user_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='app.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studetclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='app.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher', to='app.teacher'),
        ),
    ]
